### ISSUE TITLE
Websocket Events

### ISSUE THREAD

**Issue by dmitry-sinina** [virtualizm/virtualizm-ui#1]
Backend able to broadcast VM state changes over WS connection. WS connection url is **/ws_events**.
Event payload example:
```
{"type":"update_virtual_machine","payload":{"id":"0ca7303a-fd0a-4d2a-bba5-19960fd98cf6","hypervisor_id":2,"attributes":{"state":"SHUTDOWN"}}}
{"type":"update_virtual_machine","payload":{"id":"0ca7303a-fd0a-4d2a-bba5-19960fd98cf6","hypervisor_id":2,"attributes":{"state":"RUNNING"}}}
```

After receveing such events, application should update internal VMs state and render new data in UI

Application should try reconnect websocket if connection is lost.

**Comment by vvitto** [comment]
https://github.com/virtualizm/virtualizm-ui/pull/3
